# Generated by Django 4.1.7 on 2023-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruddjanghoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
    ]
